[build]
  command = "vite build"
  publish = "dist/public"

[build.environment]
  VITE_API_BASE_URL = "https://bismi-main.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200