services:
  - type: web
    name: bismi-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
    healthCheckPath: /api/health